# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd5333e1543bec94e98bc7e1663c94f8f2e643be5e801d5d30c7c49746daab323af1e370d69b5f156b42bea1657d2e81d2dfb130fefc64d41eb663e9c2c0e32

test:
  secret_key_base: 752ebb22f621b3acacf37ba55accb3239d7871b650bdc45bd9f654310c4355e171353f9d31b0f3c068a34299f3c8c71c65b427ab97e159fbc81ee1663d6d7729

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
